name: Deploy Marius Bot

on:
  push:
    branches:
      - master  # Deploys when code is pushed to "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t marius-bot .

      - name: Push Image to Docker Hub
        run: docker tag marius-bot ${{ secrets.DOCKER_USERNAME }}/marius-bot:latest && docker push ${{ secrets.DOCKER_USERNAME }}/marius-bot:latest

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/marius-bot:latest
            docker stop marius-bot || true
            docker rm marius-bot || true
            docker run -d --name marius-bot --restart always --env-file /home/ubuntu/.env ${{ secrets.DOCKER_USERNAME }}/marius-bot:latest
